# .github/workflows/app.yaml
name: Prices Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'models/prices/prices_tokens.sql'
  push:
    branches:
      - 'main'

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prices-test:
    runs-on: [ self-hosted, linux, spellbook ]
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: echo
        run: echo  $GITHUB_HEAD_REF

      - name: echo
        run: echo  $GITHUB_BASE_REF

      - name: Get prices diff
        shell: bash
        run: |
          git diff $(git merge-base --fork-point origin/main $GITHUB_HEAD_REF)..HEAD models/prices/prices_tokens.sql | grep '^\+ ' > other.txt

      - name: Test Variable
        run: cat other.txt

      - name: Run validations
        working-directory: scripts
        run: python token_checker.py --new_lines $PRICES_DIFF 2>&1